### ISSUE TITLE
Download button works occasionally....

### ISSUE THREAD

**Issue by Matrixxx3** [MicroDroid/youtube-download-button#5]
Hi
For a while now the download button only works occasionally. I don't know why, so I hope you can fix your wonderful app!

I have provided some examples

Thank you! :-)

(FF 70.0.1 | Win 10 proff)

**Comment by MicroDroid** [comment]
I think I pushed a working fix, let me know if it works though, I didn't test it well. Also nice flashlight.

**Comment by Matrixxx3** [comment]
Hi
I'm sorry but now the button is totally gone!
I recommend that you test the change well before posting an update ,so you don't lose any more subscribers.
Please correct!
Thanks! :-)

**Comment by MicroDroid** [comment]
oh :flushed:

**Comment by MicroDroid** [comment]
Ok, there were a LOT of things that needed updating etc., I fixed everything and pushed a fix.

I hope it works for you fine now. I did test it this time, too :P

**Comment by Matrixxx3** [comment]
Hi Yousef Sultan
Thank you very much! :-D

The button is back, but...
1) it still don't work on the video 'Senter LED....' It's the same as first "Loading...". But all the others cases is now working well.
2) It seems that AAC now is called 'mp4a.40.2'. I suppose it is still AAC format?
3) It seems that not all video options are coming up in the menu (se picture)

Is it also possible with a mp3 choice?

Thank you so much for your effort to fix this excellent app! :-)

...and maybe there eventually later will be an opportunity to download full HD also? That would realy be the topping on the cake. :-8
 
Happy new year! :-)

![P838_tn](https://user-images.githubusercontent.com/55065176/71770908-48d55700-2f33-11ea-832f-e4478c68a1a1.jpg)

**Comment by MicroDroid** [comment]
Hey,

1. It works for me on that video, maybe try again?
2. Yeah that's right. The thing is, the underlying framework I use changed its API, so I couldn't find again how to get names like 'AAC' or 'MP3', and I found that the `codecs` field there was the most appropriate field so I used it, so now you get that instead.
3. YouTube sometimes splits audio and video streams. Due to the nature of a browser extension, it's not possible to merge them on the fly. So only already-merged streams are available for downloading, and video-only streamed are stripped away.

**Comment by Matrixxx3** [comment]
Hi again :-)
I have trouble with the same bug for a couple of more web sites. Could it be a security issue to the youtube-site, since i.e. no one on this account site (https://www.youtube.com/channel/UCOl-SoA3EOoCC6A_XS4xOxQ) is working? See also pictures
Thank  you so much for a superb app!

![Skjermbilde (1000)_tn](https://user-images.githubusercontent.com/55065176/74107132-5488ee80-4b6d-11ea-9cc1-2f5d95d84444.png)
![Skjermbilde (1001)_tn](https://user-images.githubusercontent.com/55065176/74107133-581c7580-4b6d-11ea-8622-601baed3e065.png)
![Skjermbilde (1002)_tn](https://user-images.githubusercontent.com/55065176/74107135-5c489300-4b6d-11ea-8629-a7be774ade9c.png)
![Skjermbilde (1003)_tn](https://user-images.githubusercontent.com/55065176/74107137-5e125680-4b6d-11ea-8ca5-97dc2047ec5e.png)
![Skjermbilde (1004)_tn](https://user-images.githubusercontent.com/55065176/74107139-61a5dd80-4b6d-11ea-96b8-8737407de2f9.png)

**Comment by MicroDroid** [comment]
I patch this along with #7

**Comment by MicroDroid** [comment]
Please try again and reopen this if the issue persists.
